server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msvc-auth
          uri: lb://msvc-auth   # nombre del servicio en el discovery
          predicates:
              - Path=/api/auth/**
        - id: user
          uri: lb://msvc-user
          predicates:
            - Path=/api/users/**
jwt:
  secret: H5f9K3v2R8wL1Zx6Q0yT4pD7sV9uC2xMbhSDAAksdsao983sadasd3saasdasdQQWESDsdasdas
  expiration: 86400

eureka:
  client:
    register-with-eureka: false

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

