server:
  port: 9001

spring:
  application:
    name: msvc-auth
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shoppingDb
    username: tonigomez
    password: Nostromo.02
  jpa:
    hibernate:
      ddl-auto: update   # usa "update" mejor que "create-drop"
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

jwt:
  secret: H5f9K3v2R8wL1Zx6Q0yT4pD7sV9uC2xMbhSDAAksdsao983sadasd3saasdasdQQWESDsdasdas
  expiration: 86400

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka